import { 
  User, 
  UserProfile, 
  ITRFilingRecord, 
  TaxNoticeItem, 
  DocumentItem, 
  ServiceItem, 
  InvestmentItem, 
  BlogPost, 
  SupportTicket, 
  NotificationItem, 
  SubscriptionPlan 
} from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'user_demo_101',
    name: 'Vikramaditya Sharma',
    email: 'vikram.sharma@example.com',
    phone: '9876543210',
    role: 'USER',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-10T10:00:00Z',
    isVerified: true,
  },
  {
    id: 'user_expert_201',
    name: 'CA Priya Sundaram (FCA)',
    email: 'ca.priya@taxwithrohit.com',
    phone: '9811223344',
    role: 'TAX_EXPERT',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-06-15T09:30:00Z',
    isVerified: true,
  },
  {
    id: 'user_admin_301',
    name: 'Rajesh Nair (Admin)',
    email: 'admin@taxwithrohit.com',
    phone: '9899001122',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-01-01T00:00:00Z',
    isVerified: true,
  },
];

export const SEED_PROFILE: UserProfile = {
  userId: 'user_demo_101',
  fullName: 'Vikramaditya Sharma',
  email: 'vikram.sharma@example.com',
  phone: '9876543210',
  dob: '1992-05-14',
  gender: 'MALE',
  pan: 'ABCPS1234F',
  aadhaar: 'XXXX-XXXX-8921',
  address: 'Flat 402, Lotus Heights, Indiranagar',
  city: 'Bengaluru',
  state: 'Karnataka',
  pincode: '560038',
  assessmentYear: '2025-26',
  financialYear: '2024-25',
  residentialStatus: 'RESIDENT',
  employmentType: 'SALARIED',
  bankName: 'HDFC Bank Ltd',
  accountNumber: '50100492817291',
  ifscCode: 'HDFC0001234',
  accountType: 'SAVINGS',
  profileCompletion: 85,
};

export const SEED_ITR: ITRFilingRecord = {
  id: 'itr_rec_2025_01',
  userId: 'user_demo_101',
  assessmentYear: '2025-26',
  financialYear: '2024-25',
  itrType: 'ITR-1',
  status: 'IN_PROGRESS',
  progressPercent: 65,
  selectedRegime: 'NEW',
  salaryIncome: {
    employerName: 'Infosys Limited',
    grossSalary: 1450000,
    basicSalary: 725000,
    hra: 290000,
    specialAllowance: 385000,
    lta: 50000,
    standardDeduction: 75000,
    professionalTax: 2400,
    tdsDeducted: 98500,
  },
  otherIncome: {
    savingsInterest: 14500,
    fdInterest: 32000,
    dividendIncome: 8500,
    rentalIncome: 0,
    homeLoanInterestLetOut: 0,
    otherSources: 0,
  },
  businessIncome: {
    businessName: '',
    businessType: 'PRESUMPTIVE_44AD',
    grossTurnover: 0,
    grossReceipts: 0,
    declaredProfit: 0,
    expenses: 0,
    netProfit: 0,
  },
  capitalGains: [
    {
      id: 'cg_1',
      assetType: 'EQUITY_MF',
      buyDate: '2023-04-10',
      buyValue: 120000,
      sellDate: '2024-11-20',
      sellValue: 165000,
      transferExpenses: 200,
      gainType: 'LTCG',
      gainAmount: 44800,
    },
  ],
  deductions: {
    sec80C: 150000,
    sec80CCC: 0,
    sec80CCD1: 0,
    sec80CCD1B: 50000,
    sec80CCD2: 45000,
    sec80D_Self: 25000,
    sec80D_Parents: 30000,
    sec80E: 0,
    sec80EEA: 0,
    sec80G: 10000,
    sec80TTA: 10000,
    sec80TTB: 0,
    sec24b_HomeLoan: 120000,
    otherDeductions: 0,
  },
  calculatedTaxOld: {
    regime: 'OLD',
    grossTotalIncome: 1492200,
    totalExemptions: 52400,
    totalDeductions: 275000,
    taxableIncome: 1164800,
    taxSlabBreakdown: [
      { slab: 'Above ₹10,00,000', rate: '30%', tax: 49440 },
      { slab: '₹5,00,001 - ₹10,00,000', rate: '20%', tax: 100000 },
      { slab: '₹2,50,001 - ₹5,00,000', rate: '5%', tax: 12500 },
      { slab: 'Up to ₹2,50,000', rate: '0%', tax: 0 },
    ],
    basicTax: 161940,
    rebate87A: 0,
    surcharge: 0,
    healthAndEducationCess: 6478,
    totalTaxLiability: 168418,
    tdsPaid: 98500,
    advanceTaxPaid: 0,
    selfAssessmentTax: 0,
    refundOrPayable: 'PAYABLE',
    balanceAmount: 69918,
    recommendationNote: 'Old regime allows deductions like 80C, 80D, 24b Home Loan.',
  },
  calculatedTaxNew: {
    regime: 'NEW',
    grossTotalIncome: 1429800,
    totalExemptions: 75000,
    totalDeductions: 45000,
    taxableIncome: 1309800,
    taxSlabBreakdown: [
      { slab: '₹12,00,001 - ₹15,00,000', rate: '20%', tax: 21960 },
      { slab: '₹10,00,001 - ₹12,00,000', rate: '15%', tax: 30000 },
      { slab: '₹7,00,001 - ₹10,00,000', rate: '10%', tax: 30000 },
      { slab: '₹3,00,001 - ₹7,00,000', rate: '5%', tax: 20000 },
      { slab: 'Up to ₹3,00,000', rate: '0%', tax: 0 },
    ],
    basicTax: 101960,
    rebate87A: 0,
    surcharge: 0,
    healthAndEducationCess: 4078,
    totalTaxLiability: 106038,
    tdsPaid: 98500,
    advanceTaxPaid: 0,
    selfAssessmentTax: 0,
    refundOrPayable: 'PAYABLE',
    balanceAmount: 7538,
    recommendationNote: 'New regime saves ₹62,380 compared to Old Regime for your income level.',
  },
  assignedExpertId: 'user_expert_201',
  assignedExpertName: 'CA Priya Sundaram (FCA)',
  expertReviewNotes: 'Form 16 verified. Please upload Capital Gains mutual fund statement to finalize submission draft.',
  expertApproved: false,
  documentsRequired: ['Capital Gains Statement', 'Interest Certificate from HDFC'],
  documentsAttached: ['Form 16 (Infosys Ltd)', 'PAN Card', 'Aadhaar Card'],
  createdAt: '2025-06-01T08:00:00Z',
  updatedAt: '2025-06-18T14:20:00Z',
};

export const SEED_NOTICES: TaxNoticeItem[] = [
  {
    id: 'notice_101',
    userId: 'user_demo_101',
    noticeType: 'SECTION_143_1',
    assessmentYear: '2024-25',
    noticeDate: '2024-12-14',
    dinNumber: 'DIN-2024-ITD-1431-892182',
    demandAmount: 3420,
    status: 'RESPONSE_PREPARED',
    documentUrl: '#',
    fileName: 'Notice_143_1_AY2024_25.pdf',
    assignedExpertName: 'CA Priya Sundaram',
    expertAdvice: 'Mismatch identified in TDS claim on FD interest between AIS and 26AS. Rectification response drafted for e-filing portal.',
    timeline: [
      { title: 'Notice Received', description: 'Intimation u/s 143(1) uploaded by user', timestamp: '2024-12-16', completed: true },
      { title: 'Expert Assigned', description: 'Assigned to CA Priya Sundaram for review', timestamp: '2024-12-17', completed: true },
      { title: 'AIS / 26AS Reconciliation', description: 'Bank interest TDS verified against Form 26AS', timestamp: '2024-12-18', completed: true },
      { title: 'Response Ready', description: 'Online rectification response prepared for IT portal', timestamp: '2024-12-19', completed: true },
      { title: 'Resolution by ITD', description: 'Awaiting revised intimation from CPC Bengaluru', timestamp: 'Pending', completed: false },
    ],
    createdAt: '2024-12-16T11:00:00Z',
  },
];

export const SEED_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_1',
    userId: 'user_demo_101',
    name: 'Form 16 - Infosys Ltd (FY 2024-25)',
    type: 'FORM_16',
    fileSize: '1.4 MB',
    uploadDate: '2025-06-02',
    status: 'VERIFIED',
    assessmentYear: '2025-26',
    verifiedBy: 'CA Priya Sundaram',
  },
  {
    id: 'doc_2',
    userId: 'user_demo_101',
    name: 'PAN Card Copy',
    type: 'PAN_CARD',
    fileSize: '450 KB',
    uploadDate: '2025-01-12',
    status: 'VERIFIED',
    assessmentYear: 'All Years',
  },
  {
    id: 'doc_3',
    userId: 'user_demo_101',
    name: 'HDFC Savings Bank Statement',
    type: 'BANK_STATEMENT',
    fileSize: '3.2 MB',
    uploadDate: '2025-06-05',
    status: 'VERIFIED',
    assessmentYear: '2025-26',
  },
  {
    id: 'doc_4',
    userId: 'user_demo_101',
    name: 'HDFC Ergo Health Insurance Policy (80D)',
    type: 'INVESTMENT_PROOF',
    fileSize: '890 KB',
    uploadDate: '2025-06-08',
    status: 'VERIFIED',
    assessmentYear: '2025-26',
  },
  {
    id: 'doc_5',
    userId: 'user_demo_101',
    name: 'Zerodha Mutual Fund Capital Gains Statement',
    type: 'CAPITAL_GAINS_STATEMENT',
    fileSize: '1.1 MB',
    uploadDate: '2025-06-15',
    status: 'UPLOADED',
    assessmentYear: '2025-26',
  },
];

export const SEED_SERVICES: ServiceItem[] = [
  {
    id: 'srv_1',
    slug: 'income-tax',
    title: 'Income Tax Return (ITR) Filing',
    category: 'TAX_FILING',
    shortDesc: 'Expert assisted ITR filing for salaried, professionals, capital gains, foreign income, and businesses.',
    fullDesc: 'Get your Income Tax Return prepared, optimized, and reviewed by experienced Chartered Accountants. We maximize your tax refunds, verify AIS/TIS mismatches, and prepare an audit-proof submission draft with complete peace of mind.',
    icon: 'FileText',
    badge: 'Most Popular',
    pricing: {
      amount: 799,
      originalPrice: 1499,
      period: 'per filing',
      isPopular: true,
    },
    benefits: [
      '100% accurate tax calculation guarantee',
      'Maximum refund optimization (Old vs New Regime analysis)',
      'Dedicated Chartered Accountant review',
      'Form 16 auto-fetch and AIS reconciliation',
      'Year-round notice support included',
    ],
    processSteps: [
      { step: 1, title: 'Upload Documents', desc: 'Upload Form 16, bank statements, or capital gains report.' },
      { step: 2, title: 'CA Prepares Return', desc: 'Expert calculates optimal deductions and prepares your return.' },
      { step: 3, title: 'Review & Verify', desc: 'Approve draft tax computation and preview before submission.' },
      { step: 4, title: 'E-Verify & Ack', desc: 'Receive official acknowledgment and tax refund tracking.' },
    ],
    requiredDocs: ['PAN Card', 'Aadhaar Card', 'Form 16 / Salary Slips', 'Bank Statements', 'Brokerage Capital Gains Report'],
    faqs: [
      { question: 'What is the last date to file ITR for individuals?', answer: 'For non-audit individual taxpayers, the deadline is July 31st for each assessment year.' },
      { question: 'Can I file if I do not have Form 16?', answer: 'Yes! You can file using monthly salary slips, bank statements, and Form 26AS/AIS.' },
    ],
    ctaText: 'Start ITR Filing',
    ctaLink: '/itr-filing',
  },
  {
    id: 'srv_2',
    slug: 'gst',
    title: 'GST Registration & Return Filing',
    category: 'COMPLIANCE',
    shortDesc: 'End-to-end GST monthly/quarterly filings (GSTR-1, GSTR-3B, GSTR-9) and seamless registration.',
    fullDesc: 'Complete GST compliance suite for e-commerce sellers, traders, and service providers. Avoid late fees, claim 100% Input Tax Credit (ITC) with 2B reconciliation, and get expert handling for GST audits and department queries.',
    icon: 'Receipt',
    pricing: {
      amount: 1199,
      originalPrice: 2499,
      period: 'per month',
    },
    benefits: [
      'Accurate GSTR-1, 3B, and 9 filings',
      'Automated GSTR-2B Input Tax Credit reconciliation',
      'GST registration with LUT filing for exporters',
      'Response drafting for GST mismatch notices',
    ],
    processSteps: [
      { step: 1, title: 'Share Sales & Purchase Invoices', desc: 'Upload monthly invoice data or connect your billing software.' },
      { step: 2, title: 'ITC Reconciliation', desc: 'We reconcile your supplier invoices against GSTR-2B.' },
      { step: 3, title: 'Filing & Challan Generation', desc: 'We file returns on the GST portal before due dates.' },
    ],
    requiredDocs: ['GST Certificate', 'Sales Register', 'Purchase Invoices', 'Bank Statement', 'Digital Signature (DSC)'],
    faqs: [
      { question: 'Who needs mandatory GST registration?', answer: 'Businesses with turnover exceeding ₹40 Lakhs for goods (₹20 Lakhs for services) or engaging in inter-state commerce.' },
    ],
    ctaText: 'Get GST Support',
    ctaLink: '/services/gst',
  },
  {
    id: 'srv_3',
    slug: 'tds',
    title: 'TDS Filing & Form 16 Generation',
    category: 'COMPLIANCE',
    shortDesc: 'Quarterly TDS return filing (24Q, 26Q, 27Q, 27EQ) and TRACES Form 16/16A generation.',
    fullDesc: 'Ensure zero TDS penalty with timely computation, challan payment verification, quarterly TRACES return preparation, and bulk Form 16 Part A & B generation for your employees and vendors.',
    icon: 'Percent',
    pricing: {
      amount: 999,
      originalPrice: 1999,
      period: 'per quarter',
    },
    benefits: [
      'Quarterly Form 24Q & 26Q preparation',
      'Challan validation against OLTAS database',
      'Automatic Form 16 / 16A download from TRACES',
      'Correction returns for PAN mismatches',
    ],
    processSteps: [
      { step: 1, title: 'Upload Salary & Deduction sheets', desc: 'Provide TDS deductions and challan payment details.' },
      { step: 2, title: 'File FVU on TRACES', desc: 'We generate and submit FVU files on the NSDL portal.' },
      { step: 3, title: 'Issue Certificates', desc: 'Download digitally signed Form 16/16A certificates.' },
    ],
    requiredDocs: ['TAN Registration Certificate', 'TDS Challan Receipts', 'Deductee PAN Master', 'Salary/Payment register'],
    faqs: [
      { question: 'What is the penalty for late TDS filing?', answer: 'Under Section 234E, a late fee of ₹200 per day is charged until the return is submitted.' },
    ],
    ctaText: 'File TDS Returns',
    ctaLink: '/services/tds',
  },
  {
    id: 'srv_4',
    slug: 'tax-planning',
    title: 'Tax Planning & Advisory',
    category: 'ADVISORY',
    shortDesc: '1-on-1 strategic tax planning session with a Senior Chartered Accountant to save up to ₹1,50,000.',
    fullDesc: 'Proactive tax structuring for high-earning individuals, directors, founders, and NRIs. Restructure salary packages, utilize Section 54/54EC capital gain exemptions, and optimize business expenses legally.',
    icon: 'TrendingUp',
    pricing: {
      amount: 1499,
      originalPrice: 2999,
      period: 'per session',
      isPopular: true,
    },
    benefits: [
      'Personalized 45-minute video call with Senior CA',
      'Comprehensive Tax Savings Roadmap Report',
      'Capital gains exemption planning (Property/Shares)',
      'Salary restructuring advisory (NPS, allowances, perks)',
    ],
    processSteps: [
      { step: 1, title: 'Share Financial Profile', desc: 'Submit your CTC structure, investments, and assets.' },
      { step: 2, title: 'CA Video Consultation', desc: 'Discuss customized legal tax-saving strategies.' },
      { step: 3, title: 'Actionable Report', desc: 'Receive step-by-step implementation guide.' },
    ],
    requiredDocs: ['Latest Salary Slip', 'Investment Details', 'Asset/Property Sale details if applicable'],
    faqs: [
      { question: 'How much tax can I realistically save?', answer: 'Depending on income bracket, taxpayers frequently save between ₹30,000 to ₹1,50,000 through structured deductions.' },
    ],
    ctaText: 'Book CA Consultation',
    ctaLink: '/services/tax-planning',
  },
  {
    id: 'srv_5',
    slug: 'tax-notice',
    title: 'Tax Notice Assistance & Compliance',
    category: 'TAX_FILING',
    shortDesc: 'Defend notices under Section 143(1), 139(9), 148, 245 with professional CA representations.',
    fullDesc: 'Received a tax demand or defective notice? TaxWithRohit’s specialized litigation team analyzes the reason for discrepancy, drafts legal responses, and submits online e-proceedings to clear outstanding demands.',
    icon: 'AlertCircle',
    badge: 'Expert Assisted',
    pricing: {
      amount: 1299,
      originalPrice: 2999,
      period: 'per notice',
    },
    benefits: [
      'Comprehensive DIN and computation verification',
      'Defective return rectification (Sec 139(9))',
      'Mismatch resolution with Form 26AS and AIS',
      'E-proceedings drafting on the IT portal',
    ],
    processSteps: [
      { step: 1, title: 'Upload Notice PDF', desc: 'Upload the intimation or notice received from the IT Department.' },
      { step: 2, title: 'Diagnosis & Computation', desc: 'Our CA identifies root cause discrepancies.' },
      { step: 3, title: 'Draft & Submit Response', desc: 'We upload the legally compliant response on e-filing portal.' },
    ],
    requiredDocs: ['Copy of Notice (PDF)', 'Filed ITR-V for the relevant AY', 'Supporting bank/investment proof'],
    faqs: [
      { question: 'What is a Section 143(1) intimation?', answer: 'It is a computer-generated summary comparing your filed return against CPC data, highlighting any tax refund or demand.' },
    ],
    ctaText: 'Get Notice Help',
    ctaLink: '/tax-notices',
  },
  {
    id: 'srv_6',
    slug: 'accounting',
    title: 'Bookkeeping & Cloud Accounting',
    category: 'BUSINESS',
    shortDesc: 'Complete ledger maintenance, P&L, balance sheet, and MIS reporting for startups & SMEs.',
    fullDesc: 'Outsource your accounting to professional accountants. We handle bank reconciliations, vendor payables, customer billing, and prepare audit-ready financial statements on Zoho Books, Tally, or QuickBooks.',
    icon: 'Briefcase',
    pricing: {
      amount: 2499,
      originalPrice: 4999,
      period: 'per month',
    },
    benefits: [
      'Dedicated accountant & CA supervision',
      'Monthly Profit & Loss, Balance Sheet, and Cash Flow',
      'Daily/weekly bank reconciliations',
      'Cloud accounting software setup & management',
    ],
    processSteps: [
      { step: 1, title: 'Software Access', desc: 'Connect your Zoho, Tally, or bank feeds.' },
      { step: 2, title: 'Regular Bookkeeping', desc: 'We record invoices, expenses, and payroll monthly.' },
      { step: 3, title: 'Monthly MIS Delivery', desc: 'Receive executive reports by the 7th of every month.' },
    ],
    requiredDocs: ['Bank Statements', 'Sales & Purchase Invoices', 'Expense Receipts', 'Payroll Sheets'],
    faqs: [
      { question: 'Which accounting software do you support?', answer: 'We support Zoho Books, Tally Prime, QuickBooks, and Excel masters.' },
    ],
    ctaText: 'Explore Accounting',
    ctaLink: '/services/accounting',
  },
  {
    id: 'srv_7',
    slug: 'company-registration',
    title: 'Company & Startup Registration',
    category: 'BUSINESS',
    shortDesc: 'Pvt Ltd, LLP, OPC, Section 8, and Partnership registration with MCA approvals and DIN/DSC.',
    fullDesc: 'Launch your company with zero hassle. Includes name reservation, DIN & DSC for directors, MoA/AoA drafting, PAN & TAN allotment, Startup India recognition, and corporate bank account opening assistance.',
    icon: 'Building2',
    pricing: {
      amount: 4999,
      originalPrice: 8999,
      period: 'all inclusive',
    },
    benefits: [
      'Fast 7-10 day MCA incorporation',
      'Digital Signatures (DSC) & Director Identification Numbers (DIN)',
      'MoA & AoA drafting by corporate legal experts',
      'Free PAN, TAN, and EPFO/ESIC registrations',
    ],
    processSteps: [
      { step: 1, title: 'Name Approval (RUN)', desc: 'We check trademark availability and submit SPICe+ Part A.' },
      { step: 2, title: 'Document Drafting', desc: 'We draft company charters (MoA/AoA) and director affidavits.' },
      { step: 3, title: 'Certificate of Incorporation', desc: 'Receive your official CIN certificate, PAN & TAN.' },
    ],
    requiredDocs: ['PAN & Aadhaar of all Directors', 'Passport size photos', 'Registered Office Electricity Bill & NOC'],
    faqs: [
      { question: 'How many directors are required for Private Limited?', answer: 'A minimum of 2 directors and 2 shareholders are required (they can be the same people).' },
    ],
    ctaText: 'Register Company',
    ctaLink: '/services/company-registration',
  },
  {
    id: 'srv_8',
    slug: 'business-cfo',
    title: 'My Biz CFO (Virtual CFO Services)',
    category: 'BUSINESS',
    shortDesc: 'Strategic financial leadership, cash flow modeling, fundraising support, and board reporting.',
    fullDesc: 'Get senior finance leadership at a fraction of full-time cost. Our Virtual CFOs oversee budget forecasts, unit economics, investor decks, compliance audits, and strategic M&A planning.',
    icon: 'ShieldCheck',
    pricing: {
      amount: 9999,
      originalPrice: 18000,
      period: 'per month',
    },
    benefits: [
      'Senior CFO with 15+ years enterprise experience',
      'Monthly financial strategy & board meetings',
      'Cash runway planning and burn optimization',
      'Investor due diligence & financial modeling',
    ],
    processSteps: [
      { step: 1, title: 'Financial Diagnostic', desc: 'We audit your historical financials and metrics.' },
      { step: 2, title: 'Strategic Roadmap', desc: 'Set up KPIs, cash forecasts, and unit economics.' },
      { step: 3, title: 'Continuous Execution', desc: 'Weekly reviews, monthly board presentations, and governance.' },
    ],
    requiredDocs: ['3-year Financials', 'Cap Table', 'MIS reports'],
    faqs: [
      { question: 'Who is Virtual CFO ideal for?', answer: 'Growth-stage startups and SMEs with ₹1 Cr to ₹50 Cr revenue needing strategic finance expertise.' },
    ],
    ctaText: 'Hire Virtual CFO',
    ctaLink: '/services/business-cfo',
  },
];

export const SEED_INVESTMENTS: InvestmentItem[] = [
  {
    id: 'inv_1',
    userId: 'user_demo_101',
    category: 'ELSS',
    name: 'Mirae Asset ELSS Tax Saver Fund',
    investedAmount: 75000,
    currentValue: 98400,
    taxSection: '80C',
    taxSavingAchieved: 23400,
    growthPercent: 31.2,
    frequency: 'MONTHLY_SIP',
    startDate: '2023-01-15',
  },
  {
    id: 'inv_2',
    userId: 'user_demo_101',
    category: 'PPF',
    name: 'Public Provident Fund (SBI)',
    investedAmount: 75000,
    currentValue: 82500,
    taxSection: '80C',
    taxSavingAchieved: 23400,
    growthPercent: 7.1,
    frequency: 'ANNUAL',
    startDate: '2022-04-10',
  },
  {
    id: 'inv_3',
    userId: 'user_demo_101',
    category: 'NPS',
    name: 'National Pension Scheme (Tier 1)',
    investedAmount: 50000,
    currentValue: 58200,
    taxSection: '80CCD(1B)',
    taxSavingAchieved: 15600,
    growthPercent: 16.4,
    frequency: 'ANNUAL',
    startDate: '2023-08-20',
  },
  {
    id: 'inv_4',
    userId: 'user_demo_101',
    category: 'MUTUAL_FUNDS',
    name: 'Parag Parikh Flexi Cap Fund',
    investedAmount: 150000,
    currentValue: 195000,
    taxSection: 'LTCG 12.5%',
    taxSavingAchieved: 0,
    growthPercent: 30.0,
    frequency: 'MONTHLY_SIP',
    startDate: '2023-03-01',
  },
];

export const SEED_BLOGS: BlogPost[] = [
  {
    id: 'blog_1',
    slug: 'new-vs-old-tax-regime-ay-2025-26',
    title: 'New vs Old Tax Regime for AY 2025-26: Which One Saves You More Tax?',
    excerpt: 'Detailed comparison of tax slabs, ₹75,000 standard deduction, Section 87A rebate, and deduction break-even analysis.',
    content: `Choosing between the New Tax Regime (Section 115BAC) and Old Tax Regime is one of the most critical decisions for Indian taxpayers.

### 1. New Tax Regime Highlights (AY 2025-26)
* **Standard Deduction**: Increased to **₹75,000** for salaried employees.
* **Tax-Free Income**: Taxable income up to **₹7,00,000** attracts zero tax thanks to Section 87A rebate.
* **Streamlined Slabs**: Slabs are wider with rates starting from 5% up to 30%.

### 2. Slabs Comparison
| Income Range | New Regime Rate | Old Regime Rate |
|---|---|---|
| Up to ₹2.5L / ₹3.0L | 0% | 0% |
| ₹3L - ₹5L / ₹7L | 5% | 5% |
| ₹5L - ₹10L | 10% / 15% | 20% |
| Above ₹10L / ₹15L | 20% / 30% | 30% |

### 3. Break-Even Formula
If your total deductions (80C, 80D, 24b Home Loan, HRA) exceed **₹3.75 Lakhs to ₹4.25 Lakhs**, the Old Regime generally saves more money. Otherwise, the New Regime is cleaner and offers higher take-home salary.`,
    category: 'Tax Planning',
    author: {
      name: 'CA Priya Sundaram',
      role: 'Head of Tax Advisory',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    readTime: '6 min read',
    publishedDate: '2025-05-10',
    featuredImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    tags: ['Income Tax', 'Budget 2025', 'Tax Slabs', '80C'],
  },
  {
    id: 'blog_2',
    slug: 'how-to-read-form-16-and-avoid-mismatches',
    title: 'How to Read Form 16: Complete Step-by-Step Guide for Salaried Employees',
    excerpt: 'Understand Part A, Part B, TRACES verification, and why matching Form 16 with your AIS is crucial before filing.',
    content: `Form 16 is your certificate of tax deducted at source by your employer. Here is how to decode every section:

### Part A vs Part B
* **Part A**: Shows the employer's TAN, employee's PAN, and government deposit challan receipts.
* **Part B**: Details your total gross salary, allowances under Section 10 (HRA, LTA), standard deduction, and Chapter VI-A deductions.

### Why You Must Check AIS and Form 26AS
Before submitting your ITR, always cross-verify the TDS reported in Form 16 with TRACES 26AS and your Annual Information Statement (AIS) to avoid Section 143(1) mismatch notices.`,
    category: 'ITR Filing',
    author: {
      name: 'Rajesh Nair',
      role: 'Tax Compliance Specialist',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    readTime: '5 min read',
    publishedDate: '2025-05-22',
    featuredImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    tags: ['Form 16', 'Salaried Tax', 'TDS', 'AIS'],
  },
  {
    id: 'blog_3',
    slug: 'capital-gains-tax-rules-budget-amendments',
    title: 'Budget 2024-25 Capital Gains Tax Overhaul: Mutual Funds, Stocks, and Real Estate',
    excerpt: 'Simplified breakdown of 20% STCG, 12.5% LTCG on equity, real estate indexation changes, and how to report.',
    content: `The Union Budget introduced landmark changes to the Capital Gains taxation architecture in India.

### Key Changes:
1. **Listed Equity Shares & Equity Mutual Funds**:
   - Short Term Capital Gains (STCG) taxed at **20%**.
   - Long Term Capital Gains (LTCG) taxed at **12.5%** with exemption limit raised to **₹1.25 Lakhs**.
2. **Real Estate**:
   - LTCG rate lowered to **12.5% without indexation** for properties sold after July 23, 2024 (with grandfathering options for older properties).`,
    category: 'Investments',
    author: {
      name: 'CA Priya Sundaram',
      role: 'Head of Tax Advisory',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    readTime: '7 min read',
    publishedDate: '2025-06-01',
    featuredImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=80',
    tags: ['Capital Gains', 'Mutual Funds', 'STCG', 'LTCG'],
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'user_demo_101',
    title: 'Form 16 Verified by Expert',
    message: 'CA Priya Sundaram has successfully verified your Infosys Form 16 and matched TDS against Form 26AS.',
    type: 'DOCUMENT_REQUIRED',
    read: false,
    timestamp: '2 hours ago',
    actionUrl: '/itr-filing',
  },
  {
    id: 'notif_2',
    userId: 'user_demo_101',
    title: 'AY 2025-26 ITR Ready for Review',
    message: 'Your ITR-1 filing draft is 65% complete. Verify remaining capital gains to submit for CA sign-off.',
    type: 'ITR_REMINDER',
    read: false,
    timestamp: 'Yesterday',
    actionUrl: '/itr-filing',
  },
  {
    id: 'notif_3',
    userId: 'user_demo_101',
    title: 'Tax Notice Response Drafted',
    message: 'Response for Section 143(1) intimation has been prepared. Review details before submission to IT portal.',
    type: 'TAX_NOTICE',
    read: true,
    timestamp: '3 days ago',
    actionUrl: '/tax-notices',
  },
];

export const SEED_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tkt_101',
    userId: 'user_demo_101',
    userName: 'Vikramaditya Sharma',
    userEmail: 'vikram.sharma@example.com',
    userPhone: '9876543210',
    subject: 'Query on Section 80CCD(1B) NPS Tax Benefit in New Regime',
    category: 'ITR',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    messages: [
      {
        sender: 'USER',
        senderName: 'Vikramaditya Sharma',
        message: 'Hi, can I claim ₹50,000 additional NPS deduction under Section 80CCD(1B) if I choose the New Tax Regime?',
        timestamp: '2025-06-16T10:30:00Z',
      },
      {
        sender: 'SUPPORT_AGENT',
        senderName: 'TaxWithRohit Support (CA Team)',
        message: 'Hello Vikram, under the New Tax Regime (Section 115BAC), individual employee NPS under 80CCD(1B) is NOT deductible. However, employer contribution to NPS under Section 80CCD(2) up to 10% (or 14% for govt) of salary IS eligible in the New Regime!',
        timestamp: '2025-06-16T11:15:00Z',
      },
    ],
    createdAt: '2025-06-16T10:30:00Z',
    updatedAt: '2025-06-16T11:15:00Z',
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'FREE',
    name: 'Free Self-Filer',
    tagline: 'Ideal for single salary income & simple tax returns',
    monthlyPrice: 0,
    yearlyPrice: 0,
    features: [
      'Self ITR-1 filing preparation',
      'All 8+ Tax & Financial Calculators',
      'Basic Document Vault (50 MB)',
      'Community tax guides & blogs',
      'Standard AI Tax Assistant access',
    ],
    targetAudience: 'Individuals with single Form 16 and standard salary.',
  },
  {
    id: 'BASIC',
    name: 'Pro Tax Planner',
    tagline: 'For professionals with multiple income streams',
    monthlyPrice: 299,
    yearlyPrice: 1499,
    isPopular: false,
    features: [
      'All Free features included',
      'Capital gains & dividend calculation (ITR-2)',
      'Multiple Form 16 auto-merge',
      'Automated AIS / 26AS mismatch detector',
      'Document Vault up to 1 GB',
      'Priority email & WhatsApp support',
    ],
    targetAudience: 'Salaried techies with ESOPs, mutual funds, and stock gains.',
  },
  {
    id: 'PREMIUM',
    name: 'CA Assisted Premium',
    tagline: 'Dedicated Chartered Accountant reviews and files for you',
    monthlyPrice: 699,
    yearlyPrice: 3499,
    isPopular: true,
    features: [
      'All Pro features included',
      'Dedicated Chartered Accountant (CA) assignment',
      '1-on-1 personalized Tax Planning video call',
      '100% Audit-proof filing guarantee & refund tracking',
      'Free Notice protection & response drafting',
      'Unlimited Document Cloud storage',
      'Fast-track phone support',
    ],
    targetAudience: 'High earners, freelancers, and businesses wanting expert sign-off.',
  },
  {
    id: 'BUSINESS',
    name: 'Enterprise CFO',
    tagline: 'Complete GST, TDS, Accounting & Corporate Compliance',
    monthlyPrice: 2499,
    yearlyPrice: 19999,
    features: [
      'Complete Business suite (Pvt Ltd, LLP, Prop)',
      'Monthly GST & TDS returns included',
      'Dedicated Virtual CFO & accounting team',
      'MCA annual filings & ROC compliance',
      'Custom invoice portal & payroll integration',
      '24/7 dedicated account manager',
    ],
    targetAudience: 'Startups, SMEs, and business owners.',
  },
];
